### PR TITLE
Query node integration

### PR DESCRIPTION
**Pull request by mnaamani**
- Refactored query-node/ directory to work with latest hydra v0.0.16, (`src/` -> `mappings/`)
- Included generated files into repo.
- Added docker-compose file to work with monorepo yarn workspaces, uses our apps.Dockerfile instead of hyrdra.Dockerfile
- Moved test script runner to query-node/ folder
- Updated typedefs.json from current babylon branch build
- Resolved build errors by updating augment files to tsconfig files:
```
"paths": {
      "@polkadot/types/augment": [
        "../types/augment/all",
        "../types/augment-codec/augment-types.ts"
      ]
    }
```
- Resolved the build errors around using `createType()`
- Fixed build error in entity-helper `createVideoMediaEncoding()` => VideoMediaEncoding does not have a `happenedIn` property defined in the graphql schema!
- Added missing `typeorm` dependency.
- Finally copied `hydra-index-builder` v0.0.17-alpha package into the repo as a new workspace, and renamed it `@joystream/hydra-index-builder,` with minor tweaks. e952c9adc768cb50b1a13d4cfc9a6e71a21829cc  60e19640fa532b368c616fc9e34644743dd94ed4 

Got rid of 'ServiceNotFoundError: Service "ApiPromise" was not found, looks...'

The type of build errors that were fixed by: 149773bb2b82b50244082703eee9d60c9760f55f

```
yarn build
yarn run v1.22.4
$ tsc --build tsconfig.json
mappings/content-directory/decode.ts:27:38 - error TS2345: Argument of type '"InputPropertyValue"' is not assignable to parameter of type 'never'.

27     const propertyValue = createType('InputPropertyValue', v)
                                        ~~~~~~~~~~~~~~~~~~~~

mappings/content-directory/decode.ts:28:8 - error TS2339: Property 'asType' does not exist on type 'never'.

28       .asType('Single')
          ~~~~~~
```

Missing `happenedIn` from schema of `VideoMediaEncoding` fixed in: 9b919086785be739e4c298bd794d11ae031a655a

```
mappings/content-directory/entity-helper.ts:184:12 - error TS2339: Property 'happenedIn' does not exist on type 'VideoMediaEncoding'.

184   encoding.happenedIn = await createBlockOrGetFromDatabase(db, block)
               ~~~~~~~~~~
```

### CODE REVIEW

**Comment by mnaamani** [comment]
Is it wrong to include the generated code "from codegen"?

**Comment by mnaamani** [comment]
Seeing another problem when running db:migrate:

```
$ warthog db:migrate
Error: Command failed: /Users/mokhtar/joystream/joystream/query-node/generated/graphql-server/node_modules/.bin/ts-node /Users/mokhtar/joystream/joystream/query-node/generated/graphql-server/node_modules/.bin/typeorm migration:run  --config generated/ormconfig.ts 
Error: Cannot find module '/Users/mokhtar/joystream/joystream/query-node/generated/graphql-server/node_modules/.bin/typeorm'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at main (/Users/mokhtar/joystream/joystream/query-node/generated/graphql-server/node_modules/ts-node/src/bin.ts:227:14)
    at Object.<anonymous> (/Users/mokhtar/joystream/joystream/query-node/generated/graphql-server/node_modules/ts-node/src/bin.ts:513:3)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:676:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/mokhtar/joystream/joystream/query-node/generated/graphql-server/node_modules/.bin/ts-node /Users/mokhtar/joystream/joystream/query-node/generated/graphql-server/node_modules/.bin/typeorm migration:run  --config generated/ormconfig.ts ',
  stdout: '',
  stderr: "Error: Cannot find module '/Users/mokhtar/joystream/joystream/query-node/generated/graphql-server/node_modules/.bin/typeorm'\n" +
    '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:687:27)\n' +
    '    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)\n' +
    '    at main (/Users/mokhtar/joystream/joystream/query-node/generated/graphql-server/node_modules/ts-node/src/bin.ts:227:14)\n' +
    '    at Object.<anonymous> (/Users/mokhtar/joystream/joystream/query-node/generated/graphql-server/node_modules/ts-node/src/bin.ts:513:3)\n' +
    '    at Module._compile (internal/modules/cjs/loader.js:1015:30)\n' +
    '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)\n' +
    '    at Module.load (internal/modules/cjs/loader.js:879:32)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:724:14)\n' +
    '    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)\n'
}
```

Seems `typeorm` is missing as a dependency ?

**Comment by mnaamani** [comment]
The indexer is also exiting with error:
```
2020-10-28T12:38:17.615Z index-builder:query-node Api is ready
2020-10-28T12:38:17.616Z index-builder:redis-factory Using redis://redis:6379/0 for Redis clients
ServiceNotFoundError: Service "ApiPromise" was not found, looks like it was not registered in the container. Register it by calling Container.set("ApiPromise", ...) before using service.
    at new ServiceNotFoundError (/joystream/src/error/ServiceNotFoundError.ts:11:9)
    at ContainerInstance.getServiceValue (/joystream/src/ContainerInstance.ts:277:19)
    at ContainerInstance.get (/joystream/src/ContainerInstance.ts:109:25)
    at Object.value (/joystream/src/decorators/Inject.ts:48:42)
    at /joystream/src/ContainerInstance.ts:355:37
    at Array.map (<anonymous>)
    at ContainerInstance.initializeParams (/joystream/src/ContainerInstance.ts:352:27)
    at ContainerInstance.getServiceValue (/joystream/src/ContainerInstance.ts:305:47)
    at ContainerInstance.get (/joystream/src/ContainerInstance.ts:109:25)
    at Object.value (/joystream/src/decorators/Inject.ts:48:42)
```

**Comment by mnaamani** [comment]
- Resolved the build errors around using `createType()`
- Fixed build error in entity-helper `createVideoMediaEncoding()` => VideoMediaEncoding does not have a `happenedIn` property defined in the graphql schema!
- Added missing `typeorm` dependency.

Now the only problem that persists is https://github.com/Joystream/joystream/pull/1625#issuecomment-717905656
So the processor and indexer exit with an error.

This is likely as a result of [@dzlzv/hydra-indexer-lib](https://www.npmjs.com/package/@dzlzv/hydra-indexer-lib) depending on a newer version of `polkadot/api@2.x.x` while our monorepo workspace defines `v1.26.1` in the resolutions. https://github.com/Joystream/joystream/blob/6d124e1d23b4bc937332f82528774cc75a1e299d/package.json#L25

We can see a hint of this issue when yarn is installing dependencies.

```
warning Resolution field "@polkadot/api@1.26.1" is incompatible with requested version "@polkadot/api@^2.1.1"
```

So how do we resolve this?

1 - Update babylon branch to use @polkadot/api v2.1.1 (and fix anything that breaks in our apps)
2 - Use a modified version of hydra-indexer-lib that uses polkadot@api v1.26.1

I suspect these fixes https://github.com/Joystream/joystream/pull/1625/commits/149773bb2b82b50244082703eee9d60c9760f55f would not be required if we resolve this version conflict

**Comment by mnaamani** [comment]
So I went with second option and copied `hydra-index-builder` v0.0.17-alpha into the repo as a new workspace, and renamed it `@joystream/hydra-index-builder`, with minor tweak. Got rid of error:

`ServiceNotFoundError: Service "ApiPromise" was not found, looks like it was not registered in the container. Register it by calling Container.set("ApiPromise", ...) before using service.
`

**Review by iorveth — APPROVED** [review]
LGTM, managed to send http POST request to query node api and got a response!

**Review by metmirr — APPROVED** [review]
Looks good! I was able to run containers.

**Review by dzhelezov — APPROVED** [review]
:+1:
